//
// Copyright (c) 2017 SongCF <songcf_faith@foxmail.com>.
// file generated by proto4go
// https://github.com/golang/protobuf
//

package pb

var Code = map[string]int{
	"heartbeat_req": 20061, // heart beat
	"heartbeat_ack": 20062, // heart beat response
}

var RCode = map[int]string{
	20061: "heartbeat_req", // heart beat
	20062: "heartbeat_ack", // heart beat response
}
