//
// Copyright (c) 2017 SongCF <songcf_faith@foxmail.com>.
// file generated by proto4go
// https://github.com/songcf/proto4go
//

package pb

var Code = map[string]int{
	"heartbeat_req": 101,   // heart beat
	"heartbeat_ack": 102,   // heart beat response
	"login_req":     20061, // login
	"login_ack":     20062, // login response
}

var RCode = map[int]string{
	101:   "heartbeat_req", // heart beat
	102:   "heartbeat_ack", // heart beat response
	20061: "login_req",     // login
	20062: "login_ack",     // login response
}

const (
	CmdHeartbeatReq = 101   // heart beat
	CmdHeartbeatAck = 102   // heart beat response
	CmdLoginReq     = 20061 // login
	CmdLoginAck     = 20062 // login response
)


//define this func by yourself
var Handlers = map[int]func(*Session, []byte) (int, []byte) {
	101:     HeartbeatReq,            // heart beat
	20061:   LoginReq,                // login
}

