// Code generated by protoc-gen-go.
// source: packet.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	packet.proto

It has these top-level messages:
	Packet
	HeartbeatReq
	HeartbeatAck
	LoginReq
	LoginAck
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Packet struct {
	Cmd              *int32 `protobuf:"varint,1,req,name=cmd" json:"cmd,omitempty"`
	Vsn              *int32 `protobuf:"varint,2,req,name=vsn" json:"vsn,omitempty"`
	Payload          []byte `protobuf:"bytes,3,req,name=payload" json:"payload,omitempty"`
	Service          []byte `protobuf:"bytes,4,opt,name=service" json:"service,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Packet) Reset()                    { *m = Packet{} }
func (m *Packet) String() string            { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()               {}
func (*Packet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Packet) GetCmd() int32 {
	if m != nil && m.Cmd != nil {
		return *m.Cmd
	}
	return 0
}

func (m *Packet) GetVsn() int32 {
	if m != nil && m.Vsn != nil {
		return *m.Vsn
	}
	return 0
}

func (m *Packet) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Packet) GetService() []byte {
	if m != nil {
		return m.Service
	}
	return nil
}

// heart beat
// cmd:101
type HeartbeatReq struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *HeartbeatReq) Reset()                    { *m = HeartbeatReq{} }
func (m *HeartbeatReq) String() string            { return proto.CompactTextString(m) }
func (*HeartbeatReq) ProtoMessage()               {}
func (*HeartbeatReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// heart beat response
// cmd:102
type HeartbeatAck struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *HeartbeatAck) Reset()                    { *m = HeartbeatAck{} }
func (m *HeartbeatAck) String() string            { return proto.CompactTextString(m) }
func (*HeartbeatAck) ProtoMessage()               {}
func (*HeartbeatAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// login
// cmd:20061
type LoginReq struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *LoginReq) Reset()                    { *m = LoginReq{} }
func (m *LoginReq) String() string            { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()               {}
func (*LoginReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// login response
// cmd:20062
type LoginAck struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *LoginAck) Reset()                    { *m = LoginAck{} }
func (m *LoginAck) String() string            { return proto.CompactTextString(m) }
func (*LoginAck) ProtoMessage()               {}
func (*LoginAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*Packet)(nil), "pb.packet")
	proto.RegisterType((*HeartbeatReq)(nil), "pb.heartbeat_req")
	proto.RegisterType((*HeartbeatAck)(nil), "pb.heartbeat_ack")
	proto.RegisterType((*LoginReq)(nil), "pb.login_req")
	proto.RegisterType((*LoginAck)(nil), "pb.login_ack")
}

func init() { proto.RegisterFile("packet.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0xc9, 0x4d, 0x0e, 0xc2, 0x20,
	0x10, 0xc5, 0xf1, 0x94, 0xfa, 0x11, 0xc7, 0x1a, 0x0d, 0x2b, 0x96, 0x84, 0x55, 0x57, 0x1e, 0xa6,
	0x17, 0xd0, 0x29, 0x9d, 0x68, 0x43, 0x05, 0x04, 0x42, 0xe2, 0xed, 0x0d, 0x56, 0x4d, 0xba, 0x7b,
	0xef, 0xf7, 0x87, 0xc6, 0xa3, 0x36, 0x94, 0xce, 0x3e, 0xb8, 0xe4, 0x38, 0xf3, 0xbd, 0xba, 0xc2,
	0x66, 0x36, 0x7e, 0x82, 0x5a, 0x3f, 0x06, 0x51, 0x49, 0xd6, 0xae, 0xbb, 0x32, 0x8b, 0xe4, 0x68,
	0x05, 0x9b, 0x25, 0x47, 0xcb, 0x05, 0x6c, 0x3d, 0xbe, 0x26, 0x87, 0x83, 0xa8, 0x25, 0x6b, 0x9b,
	0xee, 0x77, 0x4b, 0x89, 0x14, 0xf2, 0xa8, 0x49, 0xac, 0x64, 0x55, 0xca, 0xf7, 0xaa, 0x23, 0x1c,
	0xee, 0x84, 0x21, 0xf5, 0x84, 0xe9, 0x12, 0xe8, 0xb9, 0x04, 0xd4, 0x46, 0xed, 0x61, 0x37, 0xb9,
	0xdb, 0x68, 0x3f, 0xf5, 0x7f, 0x50, 0x9b, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdb, 0xbd, 0x11,
	0x1c, 0xb0, 0x00, 0x00, 0x00,
}
